### PR TITLE
[BITETRAC-151] Remove React warnings in production

### PR DESCRIPTION
**Pull request by quirk0o**
https://jira.iisg.agh.edu.pl/browse/PPBITETRAC-151

@BlueEyedHush @shnek

### CODE REVIEW

**Comment by quirk0o** [comment]
That would require to add the plugin from within `gulpfile.js`. I don't think that's very elegant - having many different places for configuring webpack. When you want to make changes to webpack you have to also look through gulpfile - and that is one big file so this kind of thing would just get lost in there

**Comment by quirk0o** [comment]
Problem is we're only setting the env for server build so there's really no guarantee that the env is even set when we're building the webpack bundle

**Comment by BlueEyedHush** [comment]
I admit, I made a mistake - I though the variable is needed to be defined during build process, but the whole point is to have it declared during run. Now that I know that, I think that my comment was misguided and previous solution was preferable - sorry :)

**Comment by quirk0o** [comment]
Why do you think it was preferable? ^^

**Comment by BlueEyedHush** [comment]
Because:
1. it's strictly related to webpack, 
2. already in webpack.dconf.js there is distinction between various environments (dev/prod/karma)
First makes it better suited there and second trival to implement (as you've shown).

**Pull request merged**
