### PR TITLE
[PPBITETRAC-139] Connect groceries view to API endpoint

### PR DESCRIPTION
**Pull request by quirk0o**
https://jira.iisg.agh.edu.pl/browse/PPBITETRAC-139

@BlueEyedHush @shnek

### CODE REVIEW

**Comment by quirk0o** [comment]
1. I don't think mongoose supports anything like that (returning an id -> object map) so we would have to perform that step (mapping the array to an object) separately anyway. And in this design the backend is frontend-agnostic - it doesn't need to know what kind of format the fronted app wants.

2. Ok will do

3. 
>*1 Schema = 1 file*
>A schema should never be declared in app.js, and you should never have multiple schemas in a single file (even if you intend to nest one schema in another). While it is often expedient to inline everything into app.js, not keeping schemas in separate files makes things more difficult in the long run. Separate files lowers the barrier to entry for understanding your code base and makes tracking changes much easier.

Also I think this makes it easier to make a change if we ever decided items would be saved separately for some reason. Putting things in different files is not equivalent to them being separate entities. E.g. a best practice is to only have one React component per file but obviously most if not all components have to be part of some other higher-level component.

4. `put` does an `upsert` which means a document is updated or created if it does not exist. That could possibly come in handy? Maybe if we were saving some updates offline and then sending them to backend later?

5. that is true but changing it would mean no more pre-generated controllers. Or at least you would have to modify every controller you generate to use the extracted methods.

**Comment by BlueEyedHush** [comment]
@quirk0o 

Before answering just a word of justifications - I always comment & question things to learn authors motives. Usually I don't hold any strong opinions, it's just that I'd have done things differently (not necessarily better, just different).

Ad 1. 
* What kind of support would we need from mongoose? We just store nested documents instead of lists.
* Can't argue with the argument about API. We'd be trading POLA (Principle of Least Astonishment) for some convenience and hopefully less code.
All in all I'm certainly not going to insist - it just looks that this approach could yield slightly more elegant code.

Ad 3.
The issues really is not significant enough to warrant hot & lengthy discussion. However, I'd like to point out one thing - the quote seems to suggest that creating shitload of files doesn't have cost - it does. The more files the harder to find what you are looking for and comprehend what you are looking at - especially in language with such poor IDE support as JavaScript. With files the only organizational tool is filesystem hierarchy (hard to make it descriptive while keeping structure flat and paths short) and naming convention. 
As always, the correct balance has to be found and this usually comes down to gut feelings. If you feel this approach is OK, I'm not going to question it :)

Ad 4.
It certainly could. Since you already added it (and it works) I don't see any sensible reason to remove it. 

Ad 5. 
As I said, generating code with so much repetition doesn't seem sensible. One of the reasons for DRY is to simplify modifications - and it looks like they might be quite a lot in front of us (authentication, authorization, generic solution for lost update, ...). The fact that a looot of code repeats suggest, that we could extract quite a lot (parts specific for each path would become very small), which should lessen the impact of loosing possibility of code generation.
Please think about it carefully, because out of all 5 issues I mentiond, this one is by far the most important and it's going to heavily impact how we'll our workflow on future endpoints look like.

**Comment by quirk0o** [comment]
Ad 1.
How would you define the model then? If we wanted to use subdocuments then we would need to define its properties. And we can have an arbitrarily long amount of items. I don't really have any idea how to do that. If you do, then please explain

Ad 3.
I'll consider it :dagger: 

Ad 5. 
Ok, I'll extract those methods.

**Comment by BlueEyedHush** [comment]
Ad 1.
Well, I didn't thought about that. My lack of experience with Mongoose shows :P
The only thing I could find was disabling strict mode for our subdocument:
http://stackoverflow.com/a/23747634

**Comment by quirk0o** [comment]
Ad 1.
Doesn't seem like a good idea tbh

**Pull request merged**
